### ISSUE TITLE
[BUG]QuickShop can copy items.

### ISSUE THREAD

**Issue by tygh89071388** [mfnalex/ChestSort#131]
**Used ChestSort version**
11.2.2

**Used Spigot version**
 This server is running Paper version git-Paper-186 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 72ce684)

**Other plugin used**
https://www.spigotmc.org/resources/quickshop-reremake-1-17-ready-multi-currency.62575/

**Describe the bug**
menu preview can copy items (Use right-double-click)

**To Reproduce**
https://youtu.be/B00eRMqLO14

**Expected behavior**
FIX copy

**Additional context**
THX!

**Comment by mfnalex** [comment]
Hi, please do this:

1. `/sort debug`
2. Reproduce the bug
3. Send the console output

Then I can easily fix this. Other alternative would be that QuickShop implements a proper InventoryHolder or uses the ChestSortAPI.

**Comment by Ghost-chu** [comment]
https://github.com/Ghost-chu/QuickShop-Reremake/commit/810ca577a4232f52834b445481ef4ec11543696a

**Comment by mfnalex** [comment]
Did the QUickShop update fix it?
