### ISSUE TITLE
Consider fitting the following Folia?

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [mfnalex/ChestSort#171]
I hope your plugin will work with Folia, I love your plugin, but I'm sorry it doesn't work with Folia :(

**Comment by xiaoyueyoqwq** [comment]
> What's the issue?

No problem, your plugin works very well, I would have liked to use the feedback field in issue to report my problem, but it seems that I did not find it

**Comment by kit8379** [comment]
For plugin developers, there are a few key takeaways from the given text:

Folia introduces regionised multithreading, which means that plugins will require modification to function properly. Plugin developers should expect compatibility with existing plugins to be at zero.

Folia introduces new API additions, such as the RegionisedScheduler and EntityScheduler, which can help plugins run on the correct thread context. These additions are not compatible with Paper, but there are plans to add API to allow Folia plugins to be compatible with Paper.

To ensure compatibility with Folia, plugin developers must mark their plugin as compatible by placing "folia-supported: true" in the plugin.yml file. Additionally, plugins must take advantage of the RegionisedScheduler and EntityScheduler API to ensure correct behavior.

Plugins should not assume that they can access or modify data in other regions, as Folia regions tick in parallel and do not share data. Plugin developers should take advantage of the upcoming thread-check API to ensure correct behavior.

There are currently broken API, including the scoreboard API, and planned API changes, such as super aggressive thread checks, which may impact plugin development.

**Comment by Hutch79** [comment]
> I would have liked to use the feedback field in issue to report my problem, but it seems that I did not find it

What is your problem?

Do you ask if the Plugin works on Folia or do you ask if this is something planned for the future?

**Comment by xiaoyueyoqwq** [comment]
> > I would have liked to use the feedback field in issue to report my problem, but it seems that I did not find it
> 
> What is your problem?
> 
> Do you ask if the Plugin works on Folia or do you ask if this is something planned for the future?

No, I'd like to ask you if you're considering compatibility with the Folia client in the future, and you're probably mistaken about me

**Comment by xiaoyueyoqwq** [comment]
> > I would have liked to use the feedback field in issue to report my problem, but it seems that I did not find it
> 
> What is your problem?
> 
> Do you ask if the Plugin works on Folia or do you ask if this is something planned for the future?

hi there, have we support folia now? or it's still stay on future update plan

**Comment by mfnalex** [comment]
Anyone is free to pull request changes to support both folia and spigot, but I won‘t do that myself as I don‘t know enough about folia to properly do this myself
