### ISSUE TITLE
Hotkeys enabled in Player Warps plugin GUI **loss/duped items

### ISSUE THREAD

**Issue by guck1012** [mfnalex/ChestSort#177]
**Used ChestSort version**
13.6.3

**Used Spigot version**
JesusSpigot-169 (1.20.1)

**Other plugin used**
Player Warps 
https://www.spigotmc.org/resources/%E2%AD%90-player-warps-%E2%AD%90-%E2%9E%A2-let-your-players-set-warps-1-7-1-20.66692/

**Describe the bug**
Sorting hotkeys are allowed in Player Warps GUI, allowing for items to be duped/lost

**To Reproduce**
Use of sorting hotkeys in any GUI associated with the Player Warps plugin (/pwarp)

**Expected behavior**
Hotkeys disabled in Player Warps GUI

**Comment by mfnalex** [comment]
Sorry but what the heck is JesusSpigot

**Comment by mfnalex** [comment]
Please ask the author of the other plugin to either hook into the ChestSortAPI to disable sorting (either by cancelling the ChestSortEvent https://github.com/mfnalex/ChestSort/blob/master/HOW_TO_USE_API.md#custom-chestsort-event , or by setting the inventory unsortable manually https://github.com/mfnalex/ChestSort/blob/master/HOW_TO_USE_API.md#making-custom-inventories-sortable--unsortable ), or to use a custom inventory holder. Inventory holder class names that have "menu" or "gui" (case insensitive) in its name are automatically ignored.
