### ISSUE TITLE
Wrong repository URL in API documentation

### ISSUE THREAD

**Issue by mindw0rm** [mfnalex/ChestSort#196]
This is a documentation bug. 

[HOW_TO_USE_API.md](https://github.com/mfnalex/ChestSort/blob/master/HOW_TO_USE_API.md) says that we should use the repository `https://hub.jeff-media.com/nexus/repository/jeff-media-public/`. However, this does no longer exist. 

The correct URL seems to be `https://repo.jeff-media.com/public/`.

**Comment by mfnalex** [comment]
thx, fixed
